# Generated by Django 5.0 on 2024-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_notes_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.IntegerField(
                choices=[(1, "HR"), (2, "Lead"), (3, "Director")], max_length=1
            ),
        ),
    ]
