# Generated by Django 5.0 on 2024-01-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation",
            old_name="NetWorth",
            new_name="NetWorth_in_Cr",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.IntegerField(
                choices=[(1, "HR"), (2, "Lead"), (3, "Director")]
            ),
        ),
    ]
