# Generated by Django 5.0 on 2024-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_networth_organisation_networth_in_cr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="notes",
            field=models.TextField(),
        ),
    ]
