# Generated by Django 5.0 on 2024-01-24 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 25, 8, 19, 11, 322748)
            ),
        ),
        migrations.AddField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 25, 8, 19, 11, 322779)
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 25, 8, 19, 11, 322748)
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 25, 8, 19, 11, 322779)
            ),
        ),
    ]
