# Generated by Django 5.0 on 2024-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_notes_created_at_notes_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
