# Generated by Django 5.0 on 2024-01-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_notes_updated_at_alter_organisation_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
