# Generated by Django 5.0 on 2024-01-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_notes_updated_at_alter_organisation_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
