# Generated by Django 5.0 on 2024-01-24 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_notes_created_at_alter_notes_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
