# Generated by Django 5.0 on 2024-01-24 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_notes_updated_at_alter_organisation_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2024, 1, 24, 9, 19, 48, 24787, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
