# Generated by Django 5.0 on 2024-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_notes_created_at_alter_notes_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pet_name",
            field=models.TextField(default="admin12", unique=True),
            preserve_default=False,
        ),
    ]
