# Generated by Django 5.0 on 2024-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_customuser_pet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pet_name",
            field=models.CharField(default="allAdmins", max_length=50),
        ),
    ]
