# Generated by Django 5.0 on 2024-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_customuser_pet_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
