# Generated by Django 5.0 on 2024-01-29 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_passwordresetview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetView",
        ),
    ]
